### PR TITLE
Add position_feedback param

### PR DESCRIPTION
**Pull request by efernandez**
If position_feedback == true (default) it has current behaviour,
otherwise it uses the wheel velocity feedback to compute the odometry.

### CODE REVIEW

**Comment by efernandez** [comment]
@paulbovbel @servos @afakihcpr

**Comment by efernandez** [comment]
I've added a test for `position_feedback: false`.
All tests passed.

**Comment by paulbovbel** [comment]
LGTM

**Comment by efernandez** [comment]
@servos @afakihcpr Any comment before I merge this?

**Comment by servos** [comment]
LGTM

**Comment by afakihcpr** [comment]
LGTM

**Pull request merged**
