### PR TITLE
Sync with indigo devel upstream

### PR DESCRIPTION
**Pull request by efernandez**
Manual merge for https://github.com/clearpathrobotics/ros_controllers/pull/5, which syncs this fork with upstream indigo-devel

### CODE REVIEW

**Comment by efernandez** [comment]
@afakihcpr @servos @paulbovbel 

Only the changes for the `diff_drive_controller` are important: the manual merge only affected the `diff_drive_controller`.

**Comment by efernandez** [comment]
All test pass.

I had to increase the time to make sure the robot is stopped in the jerk tests, from `2` to `5s`.

**Comment by servos** [comment]
LGTM

**Comment by paulbovbel** [comment]
LGTM

**Comment by afakihcpr** [comment]
:+1:

**Pull request merged**
